theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/DIPlib/diplib
  zip_url: https://github.com/DIPlib/diplib/releases
  tar_url: ftp://qiftp.tudelft.nl/DIPimage
title: "DIPlib"
description: "Quantitative Image Analysis in C++, MATLAB and Python"
show_downloads: true
