github:
  repository_url: https://github.com/DIPlib/diplib
  zip_url: https://github.com/DIPlib/diplib/releases
  tar_url: /download_2.9.html
title: "DIPlib"
description: "Quantitative Image Analysis in C++, MATLAB and Python"
logo: /assets/images/DIPlib_logo.svg
show_title: false
show_downloads: true
defaults:
  -
    scope:
      path: ""
    values:
      image:
        path: /assets/images/DIPlib_social_media_preview.png
        width: 912
        height: 456
collections:
  changelogs:
    output: true
